version: '3.7'

services: 
  test-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: testservice
    ports:
      - 9010:9010
    container_name: testservice
    hostname: testservice

networks:
  default:
    external:
      name: smartheating