spring:
  application:
    name: testservice
  profiles:
    active: "dev"

server:
  port: ${PORT:9010}

---
spring:
  autoconfigure:
    exclude:    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitUser
    password: rabbitPass
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
---
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  profiles: docker
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitUser
    password: rabbitPass
eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistration:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true