spring:
  application:
    name: testservice

server:
  port: ${PORT:9010}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: false
  instance:
    preferIpAddress: true